### ISSUE TITLE
Changes to forbiddenApis.txt should trigger a Gradle task to re-run

### ISSUE THREAD

**Issue by valdisrigdon** [policeman-tools/forbidden-apis#98] opened 2016-03-01 15:02 UTC
I need to add the following to achieve this behavior. If the inputs to any `forbiddenApis` task change, it should be re-run.

```
forbiddenApisMain {
  if (file('forbiddenApis.txt').exists()) {
    inputs.file 'forbiddenApis.txt'
  }
}
```

**Comment by uschindler** [comment] 2016-03-01 15:15
This should work: How did you add the signatures files, can you post full configuration?

See https://github.com/policeman-tools/forbidden-apis/blob/master/src/main/java/de/thetaphi/forbiddenapis/gradle/CheckForbiddenApis.java#L159-L163

This getter is marked by "@InputFiles", so a change to the input files should trigger a rebuild.

**Comment by uschindler** [comment] 2016-03-01 15:19
One possible problem could be:

If you define the files using the forbiddenapis extension globally (not on task):
`forbiddenApis { signaturesFiles: .. }`

In that case forbidden apis inherits the input files fromthe global definition above. I am not sure how Gradle handles this. But anyways, this is not a bug in this task.

**Comment by valdisrigdon** [comment] 2016-03-01 16:12
This was a multi-module project. It's working now if I explicitly define it as:

```
signaturesFiles = files('forbiddenApis.txt')
```

**Comment by valdisrigdon** [comment] 2016-03-01 21:51
I think the issue was that `forbiddenApis.txt` wasn't being picked up in the sub-module; the tasks at the sub-module level were using a file at the `rootProject` level.  I'll see if I can confirm this though.

**Comment by uschindler** [comment] 2016-05-22 09:10
I close this, because it does not seem to be an issue in forbidden-apis.

**Closed by uschindler** 2016-05-22 09:10 UTC
Labels: invalid
