### ISSUE TITLE
check fails with ClassNotFoundException: org.apache.tools.ant.Task if code references code from Apache Ant

### ISSUE THREAD

**Issue by centic9** [policeman-tools/forbidden-apis#85] opened 2015-11-08 09:57 UTC
Apache POI includes some Ant-Tasks in the src/excelant/java directory. If I add the class-files from this directory to the forbidden-api-checks, I get the error below. It seems forbidden-apis-check somehow messes up the Ant-related classpath when it tries to check classes which include Ant-code themselves.

Steps to reproduce:
* Check out Apache POI
* In `build.xml`, add the line `<fileset dir="${excelant.output.dir}"/>` to the task `forbidden-apis-check`
* run `ant compile-all forbidden-apis-check`

```
ant forbidden-apis-check     
Buildfile: /opt/apache/poi/git-svn/build.xml

check-jars:

fetch-jars:

check-ooxml-jars:

fetch-ooxml-jars:

init:
     [echo] Using Java: 1.8.0_66/1.8.0_66-b17/25.66-b17/Java HotSpot(TM) 64-Bit Server VM from Oracle Corporation on Linux: 3.13.0-44-generic

forbidden-apis-check:
[forbiddenapis] Reading bundled API signatures: jdk-unsafe-1.6
[forbiddenapis] Reading bundled API signatures: jdk-deprecated-1.6
[forbiddenapis] Reading API signatures: /opt/apache/poi/git-svn/src/resources/devtools/forbidden-signatures.txt
[forbiddenapis] Loading classes to check...
[forbiddenapis] Scanning classes for violations...

BUILD FAILED
/opt/apache/poi/git-svn/build.xml:1784: Check for forbidden API calls failed: java.lang.ClassNotFoundException: org.apache.tools.ant.Task
        at de.thetaphi.forbiddenapis.Checker.getClassFromClassLoader(Checker.java:264)
        at de.thetaphi.forbiddenapis.Checker.lookupRelatedClass(Checker.java:277)
        at de.thetaphi.forbiddenapis.ClassScanner.checkClassDefinition(ClassScanner.java:149)
        at de.thetaphi.forbiddenapis.ClassScanner.checkClassDefinition(ClassScanner.java:150)
        at de.thetaphi.forbiddenapis.ClassScanner.visit(ClassScanner.java:243)
        at de.thetaphi.forbiddenapis.asm.ClassReader.accept(Unknown Source)
        at de.thetaphi.forbiddenapis.asm.ClassReader.accept(Unknown Source)
        at de.thetaphi.forbiddenapis.Checker.checkClass(Checker.java:528)
        at de.thetaphi.forbiddenapis.Checker.run(Checker.java:545)
        at de.thetaphi.forbiddenapis.ant.AntTask.execute(AntTask.java:189)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by uschindler** [comment] 2015-11-08 10:43
Hi,
this is not a bug, its really a feature. When checking classes, it does explicitely NOT add classpath from ANT to build classpath. There is also a test that checks for this.

If you have code that uses ANT classes, you have to add ANT to the classpath.

The bad guy is the following setting that is enabled for historical reasons (and ANT also warns about this in its javac task, https://ant.apache.org/manual/Tasks/javac.html):

> "includeAntRuntime": Whether to include the Ant run-time libraries in the classpath; defaults to yes, unless build.sysclasspath is set. It is usually best to set this to false so the script's behavior is not sensitive to the environment in which it is run.

forbiddenapis does not support this: It only adds to classpath what's listed in its classpath, no implicit includison of runtime.

To fix this, see Lucene's or forbiddenapis own build files which disable this setting also for javac and download a fixed version of Ant from Mavaen Central. Alternatively you can get Ant's current library from a property and add it manually to compile classpath: `${ant.core.lib}`

**Comment by uschindler** [comment] 2015-11-08 10:46
This is the test that checks for this behaviour (for good reasons): https://github.com/policeman-tools/forbidden-apis/blob/master/src/test/antunit/TestClassLoader.xml

**Comment by uschindler** [comment] 2015-11-08 10:58
Here is a patch for POI to fix the issue; I would like to close this issue as "invalid" for reasons explained above:

```diff
Index: build.xml
===================================================================
--- build.xml	(revision 1713221)
+++ build.xml	(working copy)
@@ -364,6 +364,7 @@
         <path refid="ooxml.classpath"/>
         <path refid="ooxml.xmlsec.classpath"/>
         <path path="${env.CLASSPATH}"/>
+        <path path="${ant.core.lib}"/><!-- excelant -->
     </path>
 
     <path id="lib.jacoco">
@@ -1779,10 +1780,7 @@
             <fileset dir="${main.output.dir}"/>
             <fileset dir="${ooxml.output.dir}"/>
             <fileset dir="${scratchpad.output.dir}"/>
-            <!--
-            Adding Excelant causes ClassNotFoundException, see https://github.com/policeman-tools/forbidden-apis/issues/85
             <fileset dir="${excelant.output.dir}"/>
-            -->
             <!--
             <fileset dir="${examples.output.dir}"/>
             -->
```

**Comment by uschindler** [comment] 2015-11-08 11:49
This issue is fixed by the above patch, but the problem is more another one:
The forbiddenapis classpath does not include `excelant.classpath`. I'll provide a patch for POI to fix this.

**Comment by uschindler** [comment] 2015-11-08 11:51
This is the correct patch:

```diff
Index: build.xml
===================================================================
--- build.xml	(revision 1713221)
+++ build.xml	(working copy)
@@ -363,6 +363,7 @@
         <path refid="scratchpad.classpath"/>
         <path refid="ooxml.classpath"/>
         <path refid="ooxml.xmlsec.classpath"/>
+        <path refid="excelant.classpath"/>
         <path path="${env.CLASSPATH}"/>
     </path>
 
@@ -1779,10 +1780,7 @@
             <fileset dir="${main.output.dir}"/>
             <fileset dir="${ooxml.output.dir}"/>
             <fileset dir="${scratchpad.output.dir}"/>
-            <!--
-            Adding Excelant causes ClassNotFoundException, see https://github.com/policeman-tools/forbidden-apis/issues/85
             <fileset dir="${excelant.output.dir}"/>
-            -->
             <!--
             <fileset dir="${examples.output.dir}"/>
             -->
```

**Comment by uschindler** [comment] 2015-11-08 12:00
In fact, the bug was in POI, I'll close this issue. Was a problem of incomplete classpath.

**Closed by uschindler** 2015-11-08 12:00 UTC
